# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'CourseworkChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxCocoa',    '~> 5.0'
  pod 'RxDataSources', '~> 4.0'
  pod 'MessageKit', '~> 3.3'

  # Pods for CourseworkChat

end
